[package]
name = "scratchstack-core"
description = "Core types for Scratchstack services"
keywords = ["AWS"]

authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[features]
default = ["axum"]
axum = ["dep:axum", "dep:quick-xml"]
tls = ["axum", "dep:tokio-rustls", "tokio/net"]

[dependencies]
axum = { workspace = true, optional = true }
bon.workspace = true
chrono = { workspace = true, features = ["clock", "std"] }
form_urlencoded.workspace = true
http.workspace = true
log.workspace = true
quick-xml = { workspace = true, optional = true, features = ["serialize"] }
rand = { workspace = true, features = ["std", "std_rng"] }
scratchstack-hakari = { path = "../scratchstack-hakari" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-rustls = { workspace = true, optional = true }
uuid = { workspace = true, features = ["serde", "v7"] }

[dev-dependencies]
pretty_assertions.workspace = true
serde_json.workspace = true
test-log.workspace = true
