version: "3.7"
services:
  scratchstack-iam:
    build:
      context: .
      dockerfile: Dockerfile
  postgres:
    image: postgres:12
    ports:
      - target: 5432
        published: 10811
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./schema/postgres
        target: /docker-entrypoint-initdb.d
        read_only: true
