version: "3.7"
services:
  # scratchstack-iam:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  postgres:
    image: postgres:14
    env_file: .env
    ports:
      - target: 5432
        published: 10811
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
  
