[package]
name = "scratchstack-http-framework"
description = "HTTP framework for Scratchstack services"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[features]
default = ["axum"]
axum = ["dep:axum"]
tls = ["axum", "scratchstack-core/tls"]

[dependencies]
axum = { workspace = true, optional = true }
bon.workspace = true
bytes.workspace = true
chrono = { workspace = true, features = ["clock", "std"] }
http.workspace = true
http-body.workspace = true
log.workspace = true
quick-xml = { workspace = true, features = ["serialize"] }
scratchstack-aws-principal.path = "../scratchstack-aws-principal"
scratchstack-aws-signature = { path = "../scratchstack-aws-signature", features = [
    "unstable",
] }
scratchstack-core.path = "../scratchstack-core"
scratchstack-hakari = { path = "../scratchstack-hakari" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt"] }
tower.workspace = true

[dev-dependencies]
env_logger.workspace = true
http-body-util.workspace = true
pretty_assertions.workspace = true
regex.workspace = true
test-log.workspace = true
