[package]
name = "scratchstack-bootstrap"
description = "Scratchstack bootstrap utility for creating initial users"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[[bin]]
name = "ssbs"
path = "src/ssbs.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
chrono.workspace = true
env_logger.workspace = true
log.workspace = true
rpassword.workspace = true
scratchstack-central-database = { workspace = true, features = ["utils"] }
scratchstack-cli-utils.workspace = true
scratchstack-core.workspace = true
scratchstack-hakari.workspace = true
scratchstack-shapes-cloud.workspace = true
scratchstack-shapes-iam.workspace = true
scratchstack-shapes-sts.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx = { workspace = true, features = [
    "chrono",
    "macros",
    "migrate",
    "postgres",
    "runtime-tokio",
    "tls-rustls",
] }
tokio = { workspace = true, features = ["macros", "rt"] }
whoami.workspace = true

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
