[package]
name = "scratchstack-aws-signature-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
bytes = "1.2"
chrono = { version = "0.4", default-features = false }
libfuzzer-sys = "0.4"
scratchstack-aws-principal = { path = "../../scratchstack-aws-principal" }
scratchstack-aws-signature = { path = ".." }
scratchstack-core = { path = "../../scratchstack-core", default-features = false }
tokio = { version = "1.49", features = ["rt"] }
tower = { version = "0.5", features = ["util"] }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "signature"
path = "fuzz_targets/signature.rs"
test = false
doc = false
