[package]
name = "scratchstack-iam-database"
description = "IAM database schema and types for Scratchstack services"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[features]
default = ["gsk-direct", "utils"]
gsk-direct = []
utils = ["dep:postgresql_commands", "dep:postgresql_embedded", "dep:tempfile"]

[dependencies]
ascii-casing = { workspace = true, features = ["serde"] }
aws-smithy-types.workspace = true
base32.workspace = true
base64.workspace = true
clap = { workspace = true, optional = true, features = ["derive"] }
chrono = { workspace = true, features = ["clock", "serde", "std"] }
derive_builder.workspace = true
futures.workspace = true
hex.workspace = true
indoc.workspace = true
log.workspace = true
pct-str.workspace = true
postgresql_commands = { workspace = true, optional = true }
postgresql_embedded = { workspace = true, optional = true, features = [ "rustls", "theseus", "tokio" ] }
rand = { workspace = true, features = ["std", "std_rng"] }
regex.workspace = true
scratchstack-arn = { path = "../scratchstack-arn", features = ["iam"] }
scratchstack-aspen.path = "../scratchstack-aspen"
scratchstack-aws-principal.path = "../scratchstack-aws-principal"
scratchstack-aws-signature = { path = "../scratchstack-aws-signature", features = ["unstable"] }
scratchstack-cli-utils.path = "../scratchstack-cli-utils"
scratchstack-errors.path = "../scratchstack-errors"
scratchstack-pagination.path = "../scratchstack-pagination"
scratchstack-shapes-iam.path = "../scratchstack-shapes-iam"
scratchstack-shapes-sts.path = "../scratchstack-shapes-sts"
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = [
    "chrono",
    "macros",
    "migrate",
    "postgres",
    "runtime-tokio",
    "tls-rustls",
] }
tempfile = { workspace = true, optional = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tower.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
rand = { workspace = true, features = ["thread_rng"] }
regex.workspace = true
serde_json.workspace = true
test-log.workspace = true
