//! Pagination token types and utilities.
//!
//! This crate provides a way to securely generate and decode tokens for API pagination.
//! Tokens contain one or more keys that signal where to resume querying a backend datastore from,
//! in a way that prevents tampering from clients.
//!
//! Services should still enforce their own controls on API pagination, such as ensuring a client
//! is authorized to access each item in the results generated by queries. This crate provides a
//! bit of additional defense, but should not be the only security mechanism used to validate
//! authorization.
//!
//! Tokens are encrypted using AES256-GCM. The encryption key is provided by the service, and
//! should be kept secret and rotated regularly. Multiple keys can be used in order to facilitate
//! seamless key rotation.
//!
//! Token encryption uses a context that should be unique to the API operation being paginated
//! (authenticated encryption with associated data, or AEAD). This context is used to prevent tokens
//! from being used across different services or API operations.
//!
//! In general, any type that implements [`Serialize`][serde::Serialize] can be used as the content
//! of the token or key structure. Under the hood, this crate uses the
//! [Postcard][https://docs.rs/postcard/latest/postcard/] serialization library.

use {
    aes_gcm::{AeadCore, AeadInPlace, Aes256Gcm, KeyInit as _, aead::OsRng},
    anyhow::anyhow,
    base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD},
    chrono::{DateTime, NaiveDateTime, TimeZone as _, Utc},
    derive_builder::Builder,
    lru::LruCache,
    serde::{Deserialize, Serialize},
    std::{
        collections::BTreeMap,
        fmt::{Debug, Formatter, Result as FmtResult},
        future::Future,
        num::NonZeroUsize,
        pin::Pin,
        sync::Arc,
        task::{Context, Poll},
    },
    tokio::sync::{Mutex, RwLock},
    tower::{BoxError, Service, ServiceExt as _},
    uuid::Uuid,
};

/// The size of a pagination key in bits.
pub const PAGINATION_KEY_SIZE_BITS: usize = 256;

/// The size of a pagination key in bytes.
pub const PAGINATION_KEY_SIZE: usize = PAGINATION_KEY_SIZE_BITS / 8;

/// Versions of the pagination token format. This should be incremented if any non-backwards-compatible
/// changes are made to the token format, such as changes to the encryption scheme or the structure
/// of the token content.
#[derive(Debug, Clone, Copy, Eq, Hash, PartialEq)]
#[non_exhaustive]
#[repr(u8)]
pub enum TokenVersion {
    /// The initial version of the pagination token format.
    V0 = b'0',
}

/// The current version of the pagination token format. This should be used when generating new
/// tokens.
pub const CURRENT_TOKEN_VERSION: TokenVersion = TokenVersion::V0;

/// An encryption key with associated metadata for AES-256 encryption and decryption of pagination
/// tokens.
#[derive(Builder, Clone)]
pub struct Key {
    /// An identifier for the key, included in the pagination token to allow services to determine
    /// which key to use for decryption. This should be unique across all active and retired keys
    /// to prevent ambiguity during decryption.
    #[builder(setter(into))]
    key_id: Uuid,

    /// The earliest time at which the key can be used for encryption. This allows services to
    /// prepare for key rotation by distributing new keys before they become active.
    #[builder(setter(into))]
    valid_from: DateTime<Utc>,

    /// The time at which the key can no longer be used for encryption.
    #[builder(setter(into))]
    expires_at: Option<DateTime<Utc>>,

    /// The key material for AES-256 encryption and decryption. This itself is kept encrypted in
    /// memory.
    #[builder(setter(into))]
    encrypted_key: [u8; PAGINATION_KEY_SIZE],
}

impl Key {
    /// Create a new [`KeyBuilder`] for programmatically constructing a `Key`.
    pub fn builder() -> KeyBuilder {
        KeyBuilder::default()
    }
}

impl Debug for Key {
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        f.debug_struct("Key")
            .field("key_id", &self.key_id)
            .field("valid_from", &self.valid_from)
            .field("expires_at", &self.expires_at)
            .finish()
    }
}

/// State for managing pagination tokens for a service. This generally encompasses information that
/// is independent of any specific API operation.
///
/// For Scratchstack-like services that implement AWS APIs, this includes the partition, region,
/// and service name.
pub struct ServicePaginator<C, K> {
    /// Prefix for the AAD used in token encryption that is independent of any specific API
    /// operation.
    aad_prefix: Vec<u8>,

    /// The Tower service for retrieving the current active pagination encryption key for the
    /// service.
    current_key_service: C,

    /// The Tower service for retrieving pagination encryption keys.
    key_service: K,
}

impl<C, K> Clone for ServicePaginator<C, K>
where
    C: Clone,
    K: Clone,
{
    fn clone(&self) -> Self {
        Self {
            aad_prefix: self.aad_prefix.clone(),
            current_key_service: self.current_key_service.clone(),
            key_service: self.key_service.clone(),
        }
    }
}

impl<C, K> Debug for ServicePaginator<C, K>
where
    C: Debug,
    K: Debug,
{
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        f.debug_struct("ServicePaginator")
            .field("aad_prefix", &String::from_utf8_lossy(&self.aad_prefix))
            .field("current_key_service", &self.current_key_service)
            .field("key_service", &self.key_service)
            .finish()
    }
}

impl<C, K> ServicePaginator<C, K> {
    /// Create a new `ServicePaginator` for the specified service metadata and key service.
    pub fn new<S>(service_metadata: &S, current_key_service: C, key_service: K) -> Result<Self, BoxError>
    where
        S: Serialize + ?Sized,
    {
        let aad_prefix = postcard::to_stdvec(service_metadata)?;
        Ok(Self {
            aad_prefix,
            current_key_service,
            key_service,
        })
    }
}

impl<C, K> ServicePaginator<C, K>
where
    C: Clone,
    K: Clone,
{
    /// Create an [`OperationPaginator`] for this service with the specified information about the
    /// API operation being paginated.
    pub fn operation_paginator<S>(&self, operation_metadata: &S) -> Result<OperationPaginator<C, K>, BoxError>
    where
        S: Serialize + ?Sized,
    {
        let aad_suffix = postcard::to_stdvec(operation_metadata)?;
        let mut aad = Vec::with_capacity(self.aad_prefix.len() + aad_suffix.len());
        aad.extend_from_slice(&self.aad_prefix);
        aad.extend_from_slice(&aad_suffix);
        Ok(OperationPaginator {
            aad,
            current_key_service: self.current_key_service.clone(),
            key_service: self.key_service.clone(),
        })
    }
}

/// `ScratchstackServiceMetadata` represents the metadata about a Scratchstack service that is
/// relevant for pagination token encryption. This is compromised of the partition, region, and
/// service name.
#[derive(Builder, Clone, Debug, Deserialize, Serialize)]
#[builder(setter(into))]
pub struct ScratchstackServiceMetadata {
    partition: String,
    #[builder(setter(into), default)]
    region: String,
    service_name: String,
}

impl ScratchstackServiceMetadata {
    /// Create a new `ScratchstackServiceMetadata` with the given partition, region, and service
    /// name.
    #[inline(always)]
    pub fn new(partition: impl Into<String>, region: impl Into<String>, service_name: impl Into<String>) -> Self {
        Self {
            partition: partition.into(),
            region: region.into(),
            service_name: service_name.into(),
        }
    }

    /// Creates a [`ScratchstackServiceMetadataBuilder`] for constructing a `ScratchstackServiceMetadata`.
    #[inline(always)]
    pub fn builder() -> ScratchstackServiceMetadataBuilder {
        ScratchstackServiceMetadataBuilder::default()
    }
}

/// State for managing pagination tokens for an API operation. This encompasses information about
/// the service, the version of the API, and the specific API operation being paginated.
///
/// For Scratchstack-like services that implement AWS APIs, this includes the partition, region,
/// service name, API version, and API operation name.
pub struct OperationPaginator<C, K> {
    /// The AAD used in token encryption that is specific to the API operation being paginated.
    aad: Vec<u8>,

    /// The Tower service for retrieving the current active pagination encryption key for the
    /// service.
    current_key_service: C,

    /// The Tower service for retrieving pagination encryption keys.
    key_service: K,
}

impl<C, K> Clone for OperationPaginator<C, K>
where
    C: Clone,
    K: Clone,
{
    fn clone(&self) -> Self {
        Self {
            aad: self.aad.clone(),
            current_key_service: self.current_key_service.clone(),
            key_service: self.key_service.clone(),
        }
    }
}

impl<C, K> Debug for OperationPaginator<C, K>
where
    C: Debug,
    K: Debug,
{
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        f.debug_struct("OperationPaginator")
            .field("aad", &String::from_utf8_lossy(&self.aad))
            .field("current_key_service", &self.current_key_service)
            .field("key_service", &self.key_service)
            .finish()
    }
}

impl OperationPaginator<FixedKeyService, FixedKeyService> {
    /// Create a new `OperationPaginator` that uses a fixed key for encryption and decryption. This
    /// is generally only useful for testing or other situations where a fixed key is acceptable.
    pub fn new_fixed_key<S, O>(
        service_metadata: &S,
        operation_metadata: &O,
        key_id: impl Into<Uuid>,
        encrypted_key: [u8; PAGINATION_KEY_SIZE],
    ) -> Result<Self, BoxError>
    where
        S: Serialize + ?Sized,
        O: Serialize + ?Sized,
    {
        let key_id = key_id.into();
        let current_key_service = FixedKeyService::new(key_id, encrypted_key);
        let key_service = FixedKeyService::new(key_id, encrypted_key);
        let service_paginator = ServicePaginator::new(service_metadata, current_key_service, key_service)?;
        service_paginator.operation_paginator(operation_metadata)
    }
}

impl<C, K> OperationPaginator<C, K> {
    /// Create a new `OperationPaginator` for the specified service and operation metadata.
    pub fn new<S, O>(
        service_metadata: &S,
        operation_metadata: &O,
        current_key_service: C,
        key_service: K,
    ) -> Result<Self, BoxError>
    where
        S: Serialize + ?Sized,
        O: Serialize + ?Sized,
    {
        let mut aad = postcard::to_stdvec(service_metadata)?;
        aad.extend_from_slice(&postcard::to_stdvec(operation_metadata)?);
        Ok(Self {
            aad,
            current_key_service,
            key_service,
        })
    }
}

impl<C, K> OperationPaginator<C, K> {
    /// Encrypt the provided pagination state into a pagination token.
    pub async fn encrypt_token<T>(&self, pagination_state: &T) -> Result<String, BoxError>
    where
        T: Serialize + ?Sized,
        C: Clone + Service<(), Response = Key, Error = BoxError>,
    {
        let key = self.current_key_service.clone().oneshot(()).await?;
        let cipher = Aes256Gcm::new_from_slice(&key.encrypted_key)
            .map_err(|_| anyhow!("Failed to create cipher for pagination token encryption"))?;
        let nonce = Aes256Gcm::generate_nonce(&mut OsRng);
        let mut payload = postcard::to_stdvec(pagination_state)?;
        cipher
            .encrypt_in_place(&nonce, &self.aad, &mut payload)
            .map_err(|_| anyhow!("Failed to encrypt pagination token"))?;

        // The token format is as follows:
        // [version (1 byte)] + base64([key ID (16 bytes)][nonce (12 bytes)][ciphertext (variable length)])
        let mut base64_payload = Vec::with_capacity(key.key_id.as_bytes().len() + nonce.len() + payload.len());
        base64_payload.extend_from_slice(key.key_id.as_bytes());
        base64_payload.extend_from_slice(nonce.as_slice());
        base64_payload.extend_from_slice(&payload);
        let mut result = String::with_capacity(1 + base64_payload.len() * 4 / 3 + 1);
        result.push(char::from(CURRENT_TOKEN_VERSION as u8));
        URL_SAFE_NO_PAD.encode_string(base64_payload, &mut result);

        Ok(result)
    }
}

impl<C, K> OperationPaginator<C, K>
where
    K: Clone + Service<Uuid, Response = Key, Error = BoxError>,
{
    /// Decrypt the provided pagination token into the pagination state.
    pub async fn decrypt_token<T>(&self, token: &str) -> Result<T, BoxError>
    where
        T: for<'de> Deserialize<'de>,
    {
        if token.is_empty() {
            return Err(anyhow!("Pagination token is empty").into());
        }

        let version = token.as_bytes()[0];
        if version != CURRENT_TOKEN_VERSION as u8 {
            return Err(anyhow!("Unsupported pagination token version {version}").into());
        }

        let bytes = URL_SAFE_NO_PAD.decode(&token[1..])?;
        if bytes.len() < 16 + 12 {
            return Err(anyhow!("Invalid pagination token").into());
        }

        let key_id = Uuid::from_slice(&bytes[..16])?;
        let nonce = aes_gcm::Nonce::from_slice(&bytes[16..28]);
        let ciphertext = &bytes[28..];

        let key = self.key_service.clone().oneshot(key_id).await?;
        let cipher = Aes256Gcm::new_from_slice(&key.encrypted_key)
            .map_err(|_| anyhow!("Failed to create cipher for pagination token decryption"))?;
        let mut payload = ciphertext.to_vec();
        cipher
            .decrypt_in_place(nonce, &self.aad, &mut payload)
            .map_err(|_| anyhow!("Failed to decrypt pagination token"))?;

        let state = postcard::from_bytes(&payload)?;
        Ok(state)
    }
}

/// `ScratchstackOperationMetadata` represents the metadata about a Scratchstack API operation that
/// is relevant for Scratchstack pagination token encryption. This is compromised of the API version
/// and API operation name.
#[derive(Builder, Clone, Debug, Deserialize, Serialize)]
#[builder(setter(into))]
pub struct ScratchstackOperationMetadata {
    api_version: String,
    operation: String,
}

impl ScratchstackOperationMetadata {
    /// Create a new `ScratchstackOperationMetadata` with the given API version and operation name.
    #[inline(always)]
    pub fn new(api_version: impl Into<String>, operation: impl Into<String>) -> Self {
        Self {
            api_version: api_version.into(),
            operation: operation.into(),
        }
    }

    /// Creates a [`ScratchstackOperationMetadataBuilder`] for constructing a `ScratchstackOperationMetadata`.
    #[inline(always)]
    pub fn builder() -> ScratchstackOperationMetadataBuilder {
        ScratchstackOperationMetadataBuilder::default()
    }
}

/// `FixedKeyService` provides a simple implementation of a key service that always returns the
/// same key and only supports a single key ID. This can be useful for testing or for services that
/// do not require key rotation.
#[derive(Builder, Clone, Debug)]
pub struct FixedKeyService {
    key: Key,
}

impl FixedKeyService {
    /// Create a new `FixedKeyService` with the given key material and identifier.
    pub fn new(key_id: Uuid, encrypted_key: [u8; PAGINATION_KEY_SIZE]) -> Self {
        let key = Key {
            key_id,
            // The earliest possible date representation from Chrono
            valid_from: Utc.from_utc_datetime(&NaiveDateTime::MIN),
            expires_at: None,
            encrypted_key,
        };
        Self {
            key,
        }
    }
}

impl Service<()> for FixedKeyService {
    type Response = Key;
    type Error = BoxError;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, _: ()) -> Self::Future {
        let key = self.key.clone();
        Box::pin(async move { Ok(key) })
    }
}

impl Service<Uuid> for FixedKeyService {
    type Response = Key;
    type Error = BoxError;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, key_id: Uuid) -> Self::Future {
        let key = self.key.clone();
        Box::pin(async move {
            if key.key_id == key_id {
                Ok(key)
            } else {
                Err(anyhow!("Key not found").into())
            }
        })
    }
}

/// `CachingKeyService` provides a simple implementation of a key service that wraps another key
/// service and caches keys in memory after they are retrieved. This can be useful for improving
/// performance.
pub struct CachingKeyService<C, K> {
    current_key_service: C,
    key_service: K,
    current_key: Arc<RwLock<Option<Key>>>,
    known_keys: Arc<Mutex<LruCache<Uuid, Key>>>,
}

impl<C, K> Clone for CachingKeyService<C, K>
where
    C: Clone,
    K: Clone,
{
    fn clone(&self) -> Self {
        Self {
            current_key_service: self.current_key_service.clone(),
            key_service: self.key_service.clone(),
            current_key: self.current_key.clone(),
            known_keys: self.known_keys.clone(),
        }
    }
}

impl<C, K> Debug for CachingKeyService<C, K>
where
    C: Debug,
    K: Debug,
{
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        f.debug_struct("CachingKeyService")
            .field("current_key_service", &self.current_key_service)
            .field("key_service", &self.key_service)
            .finish()
    }
}

impl<C, K> CachingKeyService<C, K> {
    /// Create a new `CachingKeyService` that wraps the provided current key service, key service,
    /// and cache capacity.
    pub fn new(current_key_service: C, key_service: K, cache_capacity: NonZeroUsize) -> Self {
        Self {
            current_key_service,
            key_service,
            current_key: Arc::new(RwLock::new(None)),
            known_keys: Arc::new(Mutex::new(LruCache::new(cache_capacity))),
        }
    }
}

impl<C, K> Service<()> for CachingKeyService<C, K>
where
    C: Clone + Service<(), Response = Key, Error = BoxError> + Send + 'static,
    <C as Service<()>>::Future: Send,
{
    type Response = Key;
    type Error = BoxError;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, _: ()) -> Self::Future {
        let current_key_service = self.current_key_service.clone();
        let current_key = self.current_key.clone();

        Box::pin(async move {
            let current_key_read = current_key.read().await;

            // If we have a cached key and it is not expired, return it.
            if let Some(key) = current_key_read.as_ref()
                && key.expires_at.map_or(true, |expires_at| expires_at > Utc::now())
            {
                return Ok(key.clone());
            }
            drop(current_key_read);

            // Otherwise, we need to retrieve the current key from the underlying service.
            let key = current_key_service.clone().oneshot(()).await?;
            let mut current_key_write = current_key.write().await;
            *current_key_write = Some(key.clone());
            Ok(key)
        })
    }
}

impl<C, K> Service<Uuid> for CachingKeyService<C, K>
where
    K: Clone + Service<Uuid, Response = Key, Error = BoxError> + Send + 'static,
    <K as Service<Uuid>>::Future: Send,
{
    type Response = Key;
    type Error = BoxError;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, key_id: Uuid) -> Self::Future {
        let key_service = self.key_service.clone();
        let known_keys = self.known_keys.clone();

        Box::pin(async move {
            let mut known_keys = known_keys.lock().await;
            if let Some(key) = known_keys.get(&key_id) {
                return Ok(key.clone());
            }

            let key = key_service.clone().oneshot(key_id).await?;
            known_keys.put(key_id, key.clone());
            Ok(key)
        })
    }
}

/// `InMemoryKeyService` provides a simple implementation of a key service that stores keys in
/// memory and supports multiple keys. This can be useful for testing or for services that do not
/// have a large number of keys to manage.
#[derive(Clone, Debug, Default)]
pub struct InMemoryKeyService {
    keys_by_id: BTreeMap<Uuid, Key>,
    keys_by_valid_from: BTreeMap<DateTime<Utc>, Key>,
}

impl InMemoryKeyService {
    /// Add a key to the service. If a key with the same ID already exists, an error is returned.
    pub fn add_key(&mut self, key: Key) -> Result<(), BoxError> {
        if self.keys_by_id.contains_key(&key.key_id) {
            return Err(anyhow!("Key with ID {} already exists", key.key_id).into());
        }

        self.keys_by_id.insert(key.key_id, key.clone());
        self.keys_by_valid_from.insert(key.valid_from, key);
        Ok(())
    }
}

impl Service<()> for InMemoryKeyService {
    type Response = Key;
    type Error = BoxError;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>>>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, _: ()) -> Self::Future {
        let keys_by_valid_from = self.keys_by_valid_from.clone();
        Box::pin(async move {
            let now = Utc::now();
            let key = keys_by_valid_from
                .range(..=now)
                .next_back()
                .ok_or_else(|| anyhow!("No valid keys available"))?
                .1
                .clone();
            Ok(key)
        })
    }
}

impl Service<Uuid> for InMemoryKeyService {
    type Response = Key;
    type Error = BoxError;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>>>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, key_id: Uuid) -> Self::Future {
        let keys_by_id = self.keys_by_id.clone();
        Box::pin(async move {
            let key = keys_by_id.get(&key_id).cloned().ok_or_else(|| anyhow!("Key with ID {} not found", key_id))?;
            Ok(key)
        })
    }
}

#[cfg(test)]
mod tests {
    use {super::*, chrono::Utc, std::num::NonZeroUsize, uuid::Uuid};

    fn make_key(key_id: Uuid, valid_from: DateTime<Utc>, expires_at: Option<DateTime<Utc>>) -> Key {
        Key {
            key_id,
            valid_from,
            expires_at,
            encrypted_key: [0u8; PAGINATION_KEY_SIZE],
        }
    }

    fn make_fixed_key_service() -> (Uuid, [u8; PAGINATION_KEY_SIZE], FixedKeyService) {
        let key_id = Uuid::new_v4();
        let encrypted_key = [42u8; PAGINATION_KEY_SIZE];
        let svc = FixedKeyService::new(key_id, encrypted_key);
        (key_id, encrypted_key, svc)
    }

    // --- FixedKeyService ---

    #[test_log::test(tokio::test)]
    async fn test_fixed_key_service_current_key() {
        let (key_id, _, svc) = make_fixed_key_service();
        let key = svc.oneshot(()).await.unwrap();
        assert_eq!(key.key_id, key_id);
    }

    #[test_log::test(tokio::test)]
    async fn test_fixed_key_service_lookup_by_id() {
        let (key_id, _, svc) = make_fixed_key_service();
        let key = svc.oneshot(key_id).await.unwrap();
        assert_eq!(key.key_id, key_id);
    }

    #[test_log::test(tokio::test)]
    async fn test_fixed_key_service_lookup_wrong_id() {
        let (_, _, svc) = make_fixed_key_service();
        let wrong_id = Uuid::new_v4();
        let result: Result<Key, _> = svc.oneshot(wrong_id).await;
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(msg.contains("not found") || msg.contains("Key"), "{msg}");
    }

    // --- InMemoryKeyService ---

    #[test_log::test]
    fn test_in_memory_key_service_add_key() {
        let mut svc = InMemoryKeyService::default();
        let key_id = Uuid::new_v4();
        let key = make_key(key_id, Utc.timestamp_opt(0, 0).unwrap(), None);
        svc.add_key(key).unwrap();
    }

    #[test_log::test]
    fn test_in_memory_key_service_add_duplicate_key() {
        let mut svc = InMemoryKeyService::default();
        let key_id = Uuid::new_v4();
        let key1 = make_key(key_id, Utc.timestamp_opt(0, 0).unwrap(), None);
        let key2 = make_key(key_id, Utc.timestamp_opt(1, 0).unwrap(), None);
        svc.add_key(key1).unwrap();
        let err = svc.add_key(key2).unwrap_err();
        assert!(err.to_string().contains("already exists"), "{err}");
    }

    #[test_log::test(tokio::test)]
    async fn test_in_memory_key_service_no_keys_error() {
        let svc = InMemoryKeyService::default();
        let result: Result<Key, _> = svc.oneshot(()).await;
        assert!(result.is_err());
    }

    #[test_log::test(tokio::test)]
    async fn test_in_memory_key_service_current_key() {
        let mut svc = InMemoryKeyService::default();
        let key_id = Uuid::new_v4();
        let key = make_key(key_id, Utc.timestamp_opt(0, 0).unwrap(), None);
        svc.add_key(key).unwrap();
        let result = svc.oneshot(()).await.unwrap();
        assert_eq!(result.key_id, key_id);
    }

    #[test_log::test(tokio::test)]
    async fn test_in_memory_key_service_latest_valid_key_selected() {
        let mut svc = InMemoryKeyService::default();
        let key_id1 = Uuid::new_v4();
        let key_id2 = Uuid::new_v4();
        let key1 = make_key(key_id1, Utc.timestamp_opt(100, 0).unwrap(), None);
        let key2 = make_key(key_id2, Utc.timestamp_opt(200, 0).unwrap(), None);
        svc.add_key(key1).unwrap();
        svc.add_key(key2).unwrap();
        let result = svc.oneshot(()).await.unwrap();
        assert_eq!(result.key_id, key_id2);
    }

    #[test_log::test(tokio::test)]
    async fn test_in_memory_key_service_future_key_not_selected() {
        let mut svc = InMemoryKeyService::default();
        let past_id = Uuid::new_v4();
        let future_id = Uuid::new_v4();
        // A key valid from the past and a key not yet valid (far future)
        let past_key = make_key(past_id, Utc.timestamp_opt(0, 0).unwrap(), None);
        let future_key = make_key(future_id, Utc.timestamp_opt(9_999_999_999, 0).unwrap(), None);
        svc.add_key(past_key).unwrap();
        svc.add_key(future_key).unwrap();
        let result = svc.oneshot(()).await.unwrap();
        assert_eq!(result.key_id, past_id);
    }

    #[test_log::test(tokio::test)]
    async fn test_in_memory_key_service_lookup_by_id() {
        let mut svc = InMemoryKeyService::default();
        let key_id = Uuid::new_v4();
        let key = make_key(key_id, Utc.timestamp_opt(0, 0).unwrap(), None);
        svc.add_key(key).unwrap();
        let result = svc.oneshot(key_id).await.unwrap();
        assert_eq!(result.key_id, key_id);
    }

    #[test_log::test(tokio::test)]
    async fn test_in_memory_key_service_lookup_wrong_id() {
        let mut svc = InMemoryKeyService::default();
        let key_id = Uuid::new_v4();
        let key = make_key(key_id, Utc.timestamp_opt(0, 0).unwrap(), None);
        svc.add_key(key).unwrap();
        let wrong_id = Uuid::new_v4();
        let result: Result<Key, _> = svc.oneshot(wrong_id).await;
        assert!(result.is_err());
    }

    // --- OperationPaginator encrypt/decrypt ---

    fn make_operation_paginator() -> OperationPaginator<FixedKeyService, FixedKeyService> {
        let key_id = Uuid::new_v4();
        let encrypted_key = [99u8; PAGINATION_KEY_SIZE];
        let svc = FixedKeyService::new(key_id, encrypted_key);
        OperationPaginator::new(&"test-service", &"ListItems", svc.clone(), svc).unwrap()
    }

    #[test_log::test(tokio::test)]
    async fn test_encrypt_decrypt_roundtrip_string() {
        let paginator = make_operation_paginator();
        let state = "cursor_value";
        let token = paginator.encrypt_token(&state).await.unwrap();
        let decoded: String = paginator.decrypt_token(&token).await.unwrap();
        assert_eq!(decoded, state);
    }

    #[test_log::test(tokio::test)]
    async fn test_encrypt_decrypt_roundtrip_struct() {
        #[derive(Debug, Deserialize, Serialize, PartialEq)]
        struct PaginationState {
            last_id: u64,
            marker: String,
        }

        let paginator = make_operation_paginator();
        let state = PaginationState {
            last_id: 12345,
            marker: "alice".to_string(),
        };
        let token = paginator.encrypt_token(&state).await.unwrap();
        let decoded: PaginationState = paginator.decrypt_token(&token).await.unwrap();
        assert_eq!(decoded, state);
    }

    #[test_log::test(tokio::test)]
    async fn test_decrypt_empty_token() {
        let paginator = make_operation_paginator();
        let result: Result<String, _> = paginator.decrypt_token("").await;
        assert!(result.is_err());
    }

    #[test_log::test(tokio::test)]
    async fn test_decrypt_wrong_version_byte() {
        let paginator = make_operation_paginator();
        // Version 'X' (0x58) is not V0 ('0' = 0x30)
        let result: Result<String, _> = paginator.decrypt_token("Xinvalid").await;
        let err = result.unwrap_err();
        assert!(err.to_string().contains("version"), "{err}");
    }

    #[test_log::test(tokio::test)]
    async fn test_decrypt_too_short_payload() {
        let paginator = make_operation_paginator();
        // Version byte '0' followed by a base64-encoded payload shorter than 28 bytes
        let short = format!("0{}", URL_SAFE_NO_PAD.encode(b"tooshort"));
        let result: Result<String, _> = paginator.decrypt_token(&short).await;
        assert!(result.is_err());
    }

    #[test_log::test(tokio::test)]
    async fn test_decrypt_wrong_aad() {
        let key_id = Uuid::new_v4();
        let encrypted_key = [99u8; PAGINATION_KEY_SIZE];
        let svc = FixedKeyService::new(key_id, encrypted_key);

        let paginator1 = OperationPaginator::new(&"test-service", &"ListItems", svc.clone(), svc.clone()).unwrap();
        let paginator2 = OperationPaginator::new(&"test-service", &"ListOtherItems", svc.clone(), svc).unwrap();

        let token = paginator1.encrypt_token(&"some_cursor").await.unwrap();
        let result: Result<String, _> = paginator2.decrypt_token(&token).await;
        assert!(result.is_err());
    }

    #[test_log::test(tokio::test)]
    async fn test_decrypt_unknown_key_id() {
        let key_id = Uuid::new_v4();
        let other_key_id = Uuid::new_v4();
        let encrypted_key = [99u8; PAGINATION_KEY_SIZE];

        let encrypt_svc = FixedKeyService::new(key_id, encrypted_key);
        let decrypt_svc = FixedKeyService::new(other_key_id, encrypted_key);

        let encrypt_paginator =
            OperationPaginator::new(&"test-service", &"ListItems", encrypt_svc.clone(), encrypt_svc).unwrap();
        let decrypt_paginator =
            OperationPaginator::new(&"test-service", &"ListItems", decrypt_svc.clone(), decrypt_svc).unwrap();

        let token = encrypt_paginator.encrypt_token(&"cursor").await.unwrap();
        let result: Result<String, _> = decrypt_paginator.decrypt_token(&token).await;
        assert!(result.is_err());
    }

    #[test_log::test(tokio::test)]
    async fn test_token_version_prefix() {
        let paginator = make_operation_paginator();
        let token = paginator.encrypt_token(&"cursor").await.unwrap();
        assert_eq!(token.as_bytes()[0], CURRENT_TOKEN_VERSION as u8);
    }

    // --- ServicePaginator ---

    #[test_log::test(tokio::test)]
    async fn test_service_paginator_roundtrip() {
        let key_id = Uuid::new_v4();
        let encrypted_key = [77u8; PAGINATION_KEY_SIZE];
        let svc = FixedKeyService::new(key_id, encrypted_key);

        let service_meta = ScratchstackServiceMetadataBuilder::default()
            .partition("aws".to_string())
            .region("us-east-1".to_string())
            .service_name("iam".to_string())
            .build()
            .unwrap();
        let service_paginator = ServicePaginator::new(&service_meta, svc.clone(), svc).unwrap();

        let op_meta = ScratchstackOperationMetadataBuilder::default()
            .api_version("2010-05-08".to_string())
            .operation("ListUsers".to_string())
            .build()
            .unwrap();
        let op_paginator = service_paginator.operation_paginator(&op_meta).unwrap();

        let state = "alice";
        let token = op_paginator.encrypt_token(&state).await.unwrap();
        let decoded: String = op_paginator.decrypt_token(&token).await.unwrap();
        assert_eq!(decoded, state);
    }

    #[test_log::test(tokio::test)]
    async fn test_service_paginator_different_operations_incompatible() {
        let key_id = Uuid::new_v4();
        let encrypted_key = [77u8; PAGINATION_KEY_SIZE];
        let svc = FixedKeyService::new(key_id, encrypted_key);

        let service_meta = ScratchstackServiceMetadataBuilder::default()
            .partition("aws".to_string())
            .region("us-east-1".to_string())
            .service_name("iam".to_string())
            .build()
            .unwrap();
        let service_paginator = ServicePaginator::new(&service_meta, svc.clone(), svc).unwrap();

        let op_meta1 = ScratchstackOperationMetadataBuilder::default()
            .api_version("2010-05-08".to_string())
            .operation("ListUsers".to_string())
            .build()
            .unwrap();
        let op_meta2 = ScratchstackOperationMetadataBuilder::default()
            .api_version("2010-05-08".to_string())
            .operation("ListGroups".to_string())
            .build()
            .unwrap();

        let op_paginator1 = service_paginator.operation_paginator(&op_meta1).unwrap();
        let op_paginator2 = service_paginator.operation_paginator(&op_meta2).unwrap();

        let token = op_paginator1.encrypt_token(&"alice").await.unwrap();
        let result: Result<String, _> = op_paginator2.decrypt_token(&token).await;
        assert!(result.is_err());
    }

    // --- CachingKeyService ---

    #[test_log::test(tokio::test)]
    async fn test_caching_key_service_current_key() {
        let (key_id, _, svc) = make_fixed_key_service();
        let caching = CachingKeyService::new(svc.clone(), svc, NonZeroUsize::new(10).unwrap());
        let key = caching.clone().oneshot(()).await.unwrap();
        assert_eq!(key.key_id, key_id);
        // Second call should use the cache
        let key2 = caching.clone().oneshot(()).await.unwrap();
        assert_eq!(key2.key_id, key_id);
    }

    #[test_log::test(tokio::test)]
    async fn test_caching_key_service_lookup_by_id() {
        let (key_id, _, svc) = make_fixed_key_service();
        let caching = CachingKeyService::new(svc.clone(), svc, NonZeroUsize::new(10).unwrap());
        let key = caching.clone().oneshot(key_id).await.unwrap();
        assert_eq!(key.key_id, key_id);
        // Second call should use the cache
        let key2 = caching.clone().oneshot(key_id).await.unwrap();
        assert_eq!(key2.key_id, key_id);
    }

    #[test_log::test(tokio::test)]
    async fn test_caching_key_service_lookup_wrong_id() {
        let (_, _, svc) = make_fixed_key_service();
        let caching = CachingKeyService::new(svc.clone(), svc, NonZeroUsize::new(10).unwrap());
        let wrong_id = Uuid::new_v4();
        let result: Result<Key, _> = caching.clone().oneshot(wrong_id).await;
        assert!(result.is_err());
    }

    // --- Key Debug format ---

    #[test_log::test]
    fn test_key_debug_hides_key_material() {
        let key_id = Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let key = Key {
            key_id,
            valid_from: Utc.timestamp_opt(0, 0).unwrap(),
            expires_at: None,
            encrypted_key: [0u8; PAGINATION_KEY_SIZE],
        };
        let debug = format!("{key:?}");
        assert!(debug.contains("550e8400-e29b-41d4-a716-446655440000"), "{debug}");
        // Key material must not appear in Debug output
        assert!(!debug.contains("encrypted_key"), "{debug}");
    }
}
