[package]
name = "scratchstack-service-common"
description = "Types and helpers shared by the Scratchstack service implementations"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bon.workspace = true
chrono.workspace = true
form_urlencoded.workspace = true
log.workspace = true
scratchstack-arn.workspace = true
scratchstack-aspen.workspace = true
scratchstack-aws-principal.workspace = true
scratchstack-aws-signature = { workspace = true, features = ["unstable"] }
scratchstack-central-database.workspace = true
scratchstack-config.workspace = true
scratchstack-core = { workspace = true, features = [
    "form",
    "http1",
    "http2",
    "macros",
    "original-uri",
    "query",
    "tls",
    "tokio",
    "tower-log",
    "tracing",
] }
scratchstack-hakari = { workspace = true }
scratchstack-shapes-iam.workspace = true
sqlx = { workspace = true, features = [
    "all-databases",
    "chrono",
    "macros",
    "migrate",
    "runtime-tokio",
    "tls-rustls",
] }
tokio = { workspace = true, features = ["net"] }
tower.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
