[package]
name = "scratchstack-service-sts"
description = "An implementation of the AWS Security Token Service"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true, features = [
    "form",
    "http1",
    "http2",
    "macros",
    "original-uri",
    "query",
    "tokio",
    "tower-log",
    "tracing",
] }
bon.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
env_logger.workspace = true
form_urlencoded.workspace = true
futures.workspace = true
http.workspace = true
http-body.workspace = true
log.workspace = true
quick-xml = { workspace = true, features = ["serialize"] }
rustls.workspace = true
scratchstack-arn.path = "../scratchstack-arn"
scratchstack-aws-signature = { path = "../scratchstack-aws-signature", features = [
    "unstable",
] }
scratchstack-aws-principal.path = "../scratchstack-aws-principal"
scratchstack-config.path = "../scratchstack-config"
scratchstack-core = { path = "../scratchstack-core", features = ["tls"] }
scratchstack-hakari = { path = "../scratchstack-hakari" }
scratchstack-iam-database.path = "../scratchstack-iam-database"
scratchstack-shapes-sts.path = "../scratchstack-shapes-sts"
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = [
    "all-databases",
    "chrono",
    "macros",
    "migrate",
    "runtime-tokio",
    "tls-rustls",
] }
tokio = { workspace = true, features = ["net", "rt-multi-thread"] }
toml.workspace = true
tower.workspace = true

[dev-dependencies]
bytes.workspace = true
form_urlencoded.workspace = true
http-body-util.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
