[package]
name = "scratchstack-service-sts"
description = "An implementation of the AWS Security Token Service"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log.workspace = true
scratchstack-arn.workspace = true
scratchstack-aspen.workspace = true
scratchstack-aws-signature = { workspace = true, features = ["unstable"] }
scratchstack-aws-principal.workspace = true
scratchstack-central-database.workspace = true
scratchstack-core = { workspace = true, features = [
    "form",
    "http1",
    "http2",
    "macros",
    "original-uri",
    "query",
    "tls",
    "tokio",
    "tower-log",
    "tracing",
] }
scratchstack-hakari.workspace = true
scratchstack-service-common.workspace = true
scratchstack-shapes-iam.workspace = true
scratchstack-shapes-sts.workspace = true
sqlx = { workspace = true, features = [
    "all-databases",
    "chrono",
    "macros",
    "migrate",
    "runtime-tokio",
    "tls-rustls",
] }

[dev-dependencies]
bytes.workspace = true
chrono.workspace = true
form_urlencoded.workspace = true
http-body-util.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
