[package]
name = "scratchstack_signature"
version = "0.1.0"
authors = [
    "David Cuthbert <dacut@kanga.org>"
]
description = "AWS Signature Verification Routines"
keywords = ["AWS", "Amazon"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4"
hex = "^0.4"
lazy_static = "^1.4.0"
regex = "^1.3"
ring = "^0.16"
